
#server:
#  port: 8070
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#server :
#  port: 8081
#
#feature:
#  2fa:
#    enabled: false
#    provider: sms
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: test
#server :
#  port: 8082
#
#feature:
#  2fa:
#    enabled: false
#    provider: email
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#server :
#  port: 8083
#
#feature:
#  2fa:
#   enabled: true
#   provider: email
#
